preserve_hierarchy: 
files:
  - source: /core/i18n/src/main/res/values/strings.xml
    translation: /core/i18n/src/main/res/values-%android_code%/%original_file_name%
    type: android
  - source: /core/i18n/src/main/res/values/units.xml
    translation: /core/i18n/src/main/res/values-%android_code%/%original_file_name%
    type: android
  - source: /plugins/sdk/src/main/res/values/strings.xml
    translation: /plugins/sdk/src/main/res/values-%android_code%/%original_file_name%
    type: android
