-keep class com.kieronquinn.app.smartspacer.sdk.**  { *; }
-dontwarn com.skydoves.balloon.ArrowPositionRules
-dontwarn com.skydoves.balloon.Balloon$Builder
-dontwarn com.skydoves.balloon.Balloon
-dontwarn com.skydoves.balloon.BalloonAnimation