package de.mm20.launcher2.ui.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightPre31DefaultColorScheme = lightColorScheme(
    primary = Color(0xFF3C6089),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD1E4FF),
    onPrimaryContainer = Color(0xFF101C2B),
    inversePrimary = Color(0xFFA6C9F8),
    secondary = Color(0xFF41617E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE5FF),
    onSecondaryContainer = Color(0xFF001D33),
    tertiary = Color(0xFF2C6674),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFB2EBFC),
    onTertiaryContainer = Color(0xFF001F26),
    background = Color(0xFFFDFCFF),
    onBackground = Color(0xFF161C27),
    surface = Color(0xFFFDFCFF),
    onSurface = Color(0xFF161C27),
    surfaceVariant = Color(0xFFD8E2FA),
    onSurfaceVariant = Color(0xFF3D475A),
    inverseSurface = Color(0xFF2B313C),
    inverseOnSurface = Color(0xFFEBF0FF),
    error = Color(0xFF98434C),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDADD),
    onErrorContainer = Color(0xFF40000E),
    outline = Color(0xFF6D778C),
)

val DarkPre31DefaultColorScheme = darkColorScheme(
    primary = Color(0xFFA6C9F8),
    onPrimary = Color(0xFF033259),
    primaryContainer = Color(0xFF234870),
    onPrimaryContainer = Color(0xFFD1E4FF),
    inversePrimary = Color(0xFF3C6089),
    secondary = Color(0xFFA9CAEC),
    onSecondary = Color(0xFF0E334E),
    secondaryContainer = Color(0xFF284965),
    onSecondaryContainer = Color(0xFFCCE5FF),
    tertiary = Color(0xFF97CFDF),
    onTertiary = Color(0xFF003641),
    tertiaryContainer = Color(0xFF094E5C),
    onTertiaryContainer = Color(0xFFB2EBFC),
    background = Color(0xFF161C27),
    onBackground = Color(0xFFDDE2F2),
    surface = Color(0xFF161C27),
    onSurface = Color(0xFFDDE2F2),
    surfaceVariant = Color(0xFF3D475A),
    onSurfaceVariant = Color(0xFFBDC7DF),
    inverseSurface = Color(0xFFDDE2F2),
    inverseOnSurface = Color(0xFF2B313C),
    error = Color(0xFFFFB3B9),
    onError = Color(0xFF5D1521),
    errorContainer = Color(0xFF7A2C36),
    onErrorContainer = Color(0xFFFFB3B9),
    outline = Color(0xFF8791A7),
)