package de.mm20.launcher2.weather

enum class WeatherIcon(val id: Int) {
    Unknown(-1),
    Clear(0),
    Cloudy(1),
    Cold(2),
    Drizzle(3),
    Haze(4),
    Fog(5),
    Hail(6),
    HeavyThunderstorm(7),
    HeavyThunderstormWithRain(8),
    Hot(9),
    MostlyCloudy(10),
    PartlyCloudy(11),
    Showers(12),
    Sleet(13),
    Snow(14),
    Storm(15),
    Thunderstorm(16),
    ThunderstormWithRain(17),
    Wind(18),
    BrokenClouds(19),
}